name: Build Geode Mod (Windows Fast)

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          combine: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LevelSolver2-Windows
          path: ${{ steps.build.outputs.output }}/*.geode

