name: Build Geode Mod (Windows Fast)

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-2022
            extra-flags: ""

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Geode CLI
        uses: geode-sdk/setup-geode@v3

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@v3
        with:
          bindings: "geode-sdk/bindings"
          combine: true
          target: ${{ matrix.config.name }}
          extra-flags: ${{ matrix.config.extra-flags }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LevelSolver2-Windows
          path: build/*.geode
